// Auto-generated by scripts/gen_mho_handlers.py.
// Hooks every function in MHOClient.exe range 0x880000..0x900000 that
// contains at least one `call [reg+0x20]` (= CCliLogicMonster vt[8] SetPosition).
// 43 entries discovered.
//
// DO NOT EDIT BY HAND - regenerate via scripts/gen_mho_handlers.py.

#include "hooks_mho_handlers.h"
#include "log.h"
#include "hook_table.h"
#include "patch.h"
#include "win_util.h"
#include "backtrace_util.h"

#include <windows.h>
#include <cstdint>

static constexpr uint32_t CCLILOGICMONSTER_VTABLE = 0x11D1F298;

static bool safe_read_u32_local(uint32_t addr, uint32_t *out) {
    if (addr < 0x10000) return false;
    SIZE_T bytes_read = 0;
    return ReadProcessMemory(GetCurrentProcess(),
                             reinterpret_cast<LPCVOID>(static_cast<uintptr_t>(addr)),
                             out, sizeof(uint32_t), &bytes_read) != 0
           && bytes_read == sizeof(uint32_t);
}

// Dedup table: each unique (func, ret) pair produces ONE backtrace, then is muted.
// Race-on-insert is harmless (worst case, two threads both log a backtrace for the
// same brand-new pair = one extra dump, no correctness issue).
static volatile int      g_seen_count = 0;
static volatile uint64_t g_seen[256];

static bool note_caller_pair_new(uint32_t func, uint32_t ret) {
    uint64_t key = ((uint64_t)func << 32) | ret;
    int n = g_seen_count;
    for (int i = 0; i < n; i++) {
        if (g_seen[i] == key) return false;
    }
    if (n >= 256) return false;
    g_seen[n] = key;
    g_seen_count = n + 1;
    return true;
}

static void log_handler_call(uint32_t func_va, HookContext *ctx) {
    uint32_t this_ptr = (uint32_t)ctx->ecx;
    uint32_t vt = 0;
    safe_read_u32_local(this_ptr, &vt);
    // vtable filter removed: ecx at applicator entry is wrapper, not CCliLogicMonster.
    DWORD *stack = hook_stack(ctx);
    uint32_t ret_addr = (uint32_t)stack[0];
    log("[MhoHandler] func=mho+0x%X this=0x%X vt=0x%X arg1=0x%X arg2=0x%X arg3=0x%X arg4=0x%X ret=0x%X tid=%lu\n",
        (unsigned)(func_va - 0x00400000),
        (unsigned)this_ptr,
        (unsigned)vt,
        (unsigned)stack[1],
        (unsigned)stack[2],
        (unsigned)stack[3],
        (unsigned)stack[4],
        (unsigned)ret_addr,
        GetCurrentThreadId());
    // First time we see this (func, ret) edge: dump the call chain so we
    // know what upstream code path led here. Subsequent hits are silent.
    if (note_caller_pair_new(func_va, ret_addr)) {
        log_caller_stack(ctx, "MhoHandler", 12);
    }
}

static const uint8_t stolen_mho_480450[] = { 0x55, 0x8B, 0xEC, 0x51, 0xA1, 0xB4, 0x00, 0xE1, 0x01 };
static const uint8_t stolen_mho_4905B0[] = { 0x55, 0x8B, 0xEC, 0x51, 0x53 };
static const uint8_t stolen_mho_490760[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x10 };
static const uint8_t stolen_mho_49BDC0[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x5C };
static const uint8_t stolen_mho_49D890[] = { 0x55, 0x8B, 0xEC, 0xA1, 0xB4, 0x00, 0xE1, 0x01 };
static const uint8_t stolen_mho_49DA90[] = { 0x55, 0x8B, 0xEC, 0xFF, 0x75, 0x08 };
static const uint8_t stolen_mho_49EEC0[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x1C };
static const uint8_t stolen_mho_49FA20[] = { 0x55, 0x8B, 0xEC, 0x81, 0xEC, 0x8C, 0x00, 0x00, 0x00 };
static const uint8_t stolen_mho_4A04F0[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x14 };
static const uint8_t stolen_mho_4A0C50[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x0C };
static const uint8_t stolen_mho_4A2B20[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x28 };
static const uint8_t stolen_mho_4A4970[] = { 0x55, 0x8B, 0xEC, 0x81, 0xEC, 0x88, 0x00, 0x00, 0x00 };
static const uint8_t stolen_mho_4A6670[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x54 };
static const uint8_t stolen_mho_4A6D40[] = { 0x55, 0x8B, 0xEC, 0x51, 0x56 };
static const uint8_t stolen_mho_4A7030[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x0C };
static const uint8_t stolen_mho_4B66C0[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x30 };
static const uint8_t stolen_mho_4B7120[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x24 };
static const uint8_t stolen_mho_4B74A0[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x18 };
static const uint8_t stolen_mho_4B7660[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x24 };
static const uint8_t stolen_mho_4BB990[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x0C };
static const uint8_t stolen_mho_4C49D0[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x0C };
static const uint8_t stolen_mho_4C4CD0[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x1C };
static const uint8_t stolen_mho_4C4EE0[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x10 };
static const uint8_t stolen_mho_4D11F0[] = { 0x55, 0x8B, 0xEC, 0x81, 0xEC, 0xA8, 0x01, 0x00, 0x00 };
static const uint8_t stolen_mho_4D6E00[] = { 0x55, 0x8B, 0xEC, 0x81, 0xEC, 0x2C, 0x0C, 0x00, 0x00 };
static const uint8_t stolen_mho_4D9DB0[] = { 0x55, 0x8B, 0xEC, 0x81, 0xEC, 0x20, 0x02, 0x00, 0x00 };
static const uint8_t stolen_mho_4DD8E0[] = { 0x55, 0x8B, 0xEC, 0x81, 0xEC, 0x98, 0x00, 0x00, 0x00 };
static const uint8_t stolen_mho_4DF2D0[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x3C };
static const uint8_t stolen_mho_4E40B0[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x34 };
static const uint8_t stolen_mho_4E7250[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x70 };
static const uint8_t stolen_mho_4E84D0[] = { 0x55, 0x8B, 0xEC, 0x81, 0xEC, 0x08, 0x01, 0x00, 0x00 };
static const uint8_t stolen_mho_4E9040[] = { 0x55, 0x8B, 0xEC, 0x51, 0x53 };
static const uint8_t stolen_mho_4EA5F0[] = { 0x55, 0x8B, 0xEC, 0x53, 0x56 };
static const uint8_t stolen_mho_4EB960[] = { 0x55, 0x8B, 0xEC, 0x8B, 0x4D, 0x08 };
static const uint8_t stolen_mho_4ECF90[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x10 };
static const uint8_t stolen_mho_4EE3C0[] = { 0x55, 0x8B, 0xEC, 0x8B, 0x55, 0x08 };
static const uint8_t stolen_mho_4EFD40[] = { 0x55, 0x8B, 0xEC, 0x81, 0xEC, 0xA4, 0x00, 0x00, 0x00 };
static const uint8_t stolen_mho_4EFFD0[] = { 0x55, 0x8B, 0xEC, 0xA1, 0x54, 0x13, 0x9B, 0x01 };
static const uint8_t stolen_mho_4F0390[] = { 0x55, 0x8B, 0xEC, 0xA1, 0x88, 0x13, 0x9B, 0x01 };
static const uint8_t stolen_mho_4F4040[] = { 0x55, 0x8B, 0xEC, 0xA1, 0xB4, 0x00, 0xE1, 0x01 };
static const uint8_t stolen_mho_4F4C30[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x10 };
static const uint8_t stolen_mho_4F9630[] = { 0x55, 0x8B, 0xEC, 0x81, 0xEC, 0x74, 0x01, 0x00, 0x00 };
static const uint8_t stolen_mho_4FBF50[] = { 0x55, 0x8B, 0xEC, 0x81, 0xEC, 0xA4, 0x00, 0x00, 0x00 };
static const uint8_t stolen_mho_4E5130[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x68 };
static const uint8_t stolen_mho_4E49E0[] = { 0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x08 };
static const uint8_t stolen_mho_493F90[] = { 0x55, 0x8B, 0xEC, 0xA1, 0xB4, 0x00, 0xE1, 0x01 };

// Per-function thunks: each carries its own VA so the shared logger can identify it.
static void cb_mho_480450(HookContext *ctx) { log_handler_call(0x00880450, ctx); }
static void cb_mho_4905B0(HookContext *ctx) { log_handler_call(0x008905B0, ctx); }
static void cb_mho_490760(HookContext *ctx) { log_handler_call(0x00890760, ctx); }
static void cb_mho_49BDC0(HookContext *ctx) { log_handler_call(0x0089BDC0, ctx); }
static void cb_mho_49D890(HookContext *ctx) { log_handler_call(0x0089D890, ctx); }
static void cb_mho_49DA90(HookContext *ctx) { log_handler_call(0x0089DA90, ctx); }
static void cb_mho_49EEC0(HookContext *ctx) { log_handler_call(0x0089EEC0, ctx); }
static void cb_mho_49FA20(HookContext *ctx) { log_handler_call(0x0089FA20, ctx); }
static void cb_mho_4A04F0(HookContext *ctx) { log_handler_call(0x008A04F0, ctx); }
static void cb_mho_4A0C50(HookContext *ctx) { log_handler_call(0x008A0C50, ctx); }
static void cb_mho_4A2B20(HookContext *ctx) { log_handler_call(0x008A2B20, ctx); }
static void cb_mho_4A4970(HookContext *ctx) { log_handler_call(0x008A4970, ctx); }
static void cb_mho_4A6670(HookContext *ctx) { log_handler_call(0x008A6670, ctx); }
static void cb_mho_4A6D40(HookContext *ctx) { log_handler_call(0x008A6D40, ctx); }
static void cb_mho_4A7030(HookContext *ctx) { log_handler_call(0x008A7030, ctx); }
static void cb_mho_4B66C0(HookContext *ctx) { log_handler_call(0x008B66C0, ctx); }
static void cb_mho_4B7120(HookContext *ctx) { log_handler_call(0x008B7120, ctx); }
static void cb_mho_4B74A0(HookContext *ctx) { log_handler_call(0x008B74A0, ctx); }
static void cb_mho_4B7660(HookContext *ctx) { log_handler_call(0x008B7660, ctx); }
static void cb_mho_4BB990(HookContext *ctx) { log_handler_call(0x008BB990, ctx); }
static void cb_mho_4C49D0(HookContext *ctx) { log_handler_call(0x008C49D0, ctx); }
static void cb_mho_4C4CD0(HookContext *ctx) { log_handler_call(0x008C4CD0, ctx); }
static void cb_mho_4C4EE0(HookContext *ctx) { log_handler_call(0x008C4EE0, ctx); }
static void cb_mho_4D11F0(HookContext *ctx) { log_handler_call(0x008D11F0, ctx); }
static void cb_mho_4D6E00(HookContext *ctx) { log_handler_call(0x008D6E00, ctx); }
static void cb_mho_4D9DB0(HookContext *ctx) { log_handler_call(0x008D9DB0, ctx); }
static void cb_mho_4DD8E0(HookContext *ctx) { log_handler_call(0x008DD8E0, ctx); }
static void cb_mho_4DF2D0(HookContext *ctx) { log_handler_call(0x008DF2D0, ctx); }
static void cb_mho_4E40B0(HookContext *ctx) { log_handler_call(0x008E40B0, ctx); }
static void cb_mho_4E7250(HookContext *ctx) { log_handler_call(0x008E7250, ctx); }
static void cb_mho_4E84D0(HookContext *ctx) { log_handler_call(0x008E84D0, ctx); }
static void cb_mho_4E9040(HookContext *ctx) { log_handler_call(0x008E9040, ctx); }
static void cb_mho_4EA5F0(HookContext *ctx) { log_handler_call(0x008EA5F0, ctx); }
static void cb_mho_4EB960(HookContext *ctx) { log_handler_call(0x008EB960, ctx); }
static void cb_mho_4ECF90(HookContext *ctx) { log_handler_call(0x008ECF90, ctx); }
static void cb_mho_4EE3C0(HookContext *ctx) { log_handler_call(0x008EE3C0, ctx); }
static void cb_mho_4EFD40(HookContext *ctx) { log_handler_call(0x008EFD40, ctx); }
static void cb_mho_4EFFD0(HookContext *ctx) { log_handler_call(0x008EFFD0, ctx); }
static void cb_mho_4F0390(HookContext *ctx) { log_handler_call(0x008F0390, ctx); }
static void cb_mho_4F4040(HookContext *ctx) { log_handler_call(0x008F4040, ctx); }
static void cb_mho_4F4C30(HookContext *ctx) { log_handler_call(0x008F4C30, ctx); }
static void cb_mho_4F9630(HookContext *ctx) { log_handler_call(0x008F9630, ctx); }
static void cb_mho_4FBF50(HookContext *ctx) { log_handler_call(0x008FBF50, ctx); }
static void cb_mho_4E5130(HookContext *ctx) { log_handler_call(0x008E5130, ctx); }
static void cb_mho_4E49E0(HookContext *ctx) { log_handler_call(0x008E49E0, ctx); }
static void cb_mho_493F90(HookContext *ctx) { log_handler_call(0x00893F90, ctx); }

// Hook table: offset is RVA from MHOClient.exe base.
static const JmpHookEntry mho_handler_jmp_hooks[] = {
    {0x00480450, cb_mho_480450, stolen_mho_480450, sizeof(stolen_mho_480450)},
    {0x004905B0, cb_mho_4905B0, stolen_mho_4905B0, sizeof(stolen_mho_4905B0)},
    {0x00490760, cb_mho_490760, stolen_mho_490760, sizeof(stolen_mho_490760)},
    {0x0049BDC0, cb_mho_49BDC0, stolen_mho_49BDC0, sizeof(stolen_mho_49BDC0)},
    // {0x0049D890, cb_mho_49D890, stolen_mho_49D890, sizeof(stolen_mho_49D890)},
    // {0x0049DA90, cb_mho_49DA90, stolen_mho_49DA90, sizeof(stolen_mho_49DA90)},
    // {0x0049EEC0, cb_mho_49EEC0, stolen_mho_49EEC0, sizeof(stolen_mho_49EEC0)},
    {0x0049FA20, cb_mho_49FA20, stolen_mho_49FA20, sizeof(stolen_mho_49FA20)},
    {0x004A04F0, cb_mho_4A04F0, stolen_mho_4A04F0, sizeof(stolen_mho_4A04F0)},
    {0x004A0C50, cb_mho_4A0C50, stolen_mho_4A0C50, sizeof(stolen_mho_4A0C50)},
    // {0x004A2B20, cb_mho_4A2B20, stolen_mho_4A2B20, sizeof(stolen_mho_4A2B20)},
    {0x004A4970, cb_mho_4A4970, stolen_mho_4A4970, sizeof(stolen_mho_4A4970)},
    {0x004A6670, cb_mho_4A6670, stolen_mho_4A6670, sizeof(stolen_mho_4A6670)},
    {0x004A6D40, cb_mho_4A6D40, stolen_mho_4A6D40, sizeof(stolen_mho_4A6D40)},
    {0x004A7030, cb_mho_4A7030, stolen_mho_4A7030, sizeof(stolen_mho_4A7030)},
    {0x004B66C0, cb_mho_4B66C0, stolen_mho_4B66C0, sizeof(stolen_mho_4B66C0)},
    {0x004B7120, cb_mho_4B7120, stolen_mho_4B7120, sizeof(stolen_mho_4B7120)},
    {0x004B74A0, cb_mho_4B74A0, stolen_mho_4B74A0, sizeof(stolen_mho_4B74A0)},
    {0x004B7660, cb_mho_4B7660, stolen_mho_4B7660, sizeof(stolen_mho_4B7660)},
    {0x004BB990, cb_mho_4BB990, stolen_mho_4BB990, sizeof(stolen_mho_4BB990)},
    {0x004C49D0, cb_mho_4C49D0, stolen_mho_4C49D0, sizeof(stolen_mho_4C49D0)},
    {0x004C4CD0, cb_mho_4C4CD0, stolen_mho_4C4CD0, sizeof(stolen_mho_4C4CD0)},
    {0x004C4EE0, cb_mho_4C4EE0, stolen_mho_4C4EE0, sizeof(stolen_mho_4C4EE0)},
    {0x004D11F0, cb_mho_4D11F0, stolen_mho_4D11F0, sizeof(stolen_mho_4D11F0)},
    {0x004D6E00, cb_mho_4D6E00, stolen_mho_4D6E00, sizeof(stolen_mho_4D6E00)},
    {0x004D9DB0, cb_mho_4D9DB0, stolen_mho_4D9DB0, sizeof(stolen_mho_4D9DB0)},
    {0x004DD8E0, cb_mho_4DD8E0, stolen_mho_4DD8E0, sizeof(stolen_mho_4DD8E0)},
    {0x004DF2D0, cb_mho_4DF2D0, stolen_mho_4DF2D0, sizeof(stolen_mho_4DF2D0)},
    {0x004E40B0, cb_mho_4E40B0, stolen_mho_4E40B0, sizeof(stolen_mho_4E40B0)},
    {0x004E7250, cb_mho_4E7250, stolen_mho_4E7250, sizeof(stolen_mho_4E7250)},
    {0x004E84D0, cb_mho_4E84D0, stolen_mho_4E84D0, sizeof(stolen_mho_4E84D0)},
    {0x004E9040, cb_mho_4E9040, stolen_mho_4E9040, sizeof(stolen_mho_4E9040)},
    {0x004EA5F0, cb_mho_4EA5F0, stolen_mho_4EA5F0, sizeof(stolen_mho_4EA5F0)},
    {0x004EB960, cb_mho_4EB960, stolen_mho_4EB960, sizeof(stolen_mho_4EB960)},
    // {0x004ECF90, cb_mho_4ECF90, stolen_mho_4ECF90, sizeof(stolen_mho_4ECF90)},
    {0x004EE3C0, cb_mho_4EE3C0, stolen_mho_4EE3C0, sizeof(stolen_mho_4EE3C0)},
    {0x004EFD40, cb_mho_4EFD40, stolen_mho_4EFD40, sizeof(stolen_mho_4EFD40)},
    // {0x004EFFD0, cb_mho_4EFFD0, stolen_mho_4EFFD0, sizeof(stolen_mho_4EFFD0)},
    // {0x004F0390, cb_mho_4F0390, stolen_mho_4F0390, sizeof(stolen_mho_4F0390)},
    {0x004F4040, cb_mho_4F4040, stolen_mho_4F4040, sizeof(stolen_mho_4F4040)},
    {0x004F4C30, cb_mho_4F4C30, stolen_mho_4F4C30, sizeof(stolen_mho_4F4C30)},
    {0x004F9630, cb_mho_4F9630, stolen_mho_4F9630, sizeof(stolen_mho_4F9630)},
    {0x004FBF50, cb_mho_4FBF50, stolen_mho_4FBF50, sizeof(stolen_mho_4FBF50)},
    {0x004E5130, cb_mho_4E5130, stolen_mho_4E5130, sizeof(stolen_mho_4E5130)},
    {0x004E49E0, cb_mho_4E49E0, stolen_mho_4E49E0, sizeof(stolen_mho_4E49E0)},
    {0x00493F90, cb_mho_493F90, stolen_mho_493F90, sizeof(stolen_mho_493F90)},
};

void install_mho_handler_hooks(DWORD mhoclient_base) {
    install_jmp_hooks(mhoclient_base, mho_handler_jmp_hooks, std::size(mho_handler_jmp_hooks));
    log("mho handler hooks: %d entries installed\n", (int)std::size(mho_handler_jmp_hooks));
}
